#!/usr/bin/gawk -f

BEGIN {
	while(("wget --quiet -O- "ARGV[1]) | getline) {
		a = split($0, b, "[;|:|&|,]")
		for(c = 1; c <= a; c++) {
			d[b[c]] = b[c + (b[c] == "pageCount" ? 3 : 5)]
			if(b[c] == "title" && ++titleCnt == 1) break
		}
	}

	"mktemp -d" | getline e
	system(("for f in $(seq "1" "d["pageCount"]"); do wget --quiet -P "e" https://image.isu.pub/"d["revisionId"]"-"d["publicationId"]"/jpg/page_${f}.jpg; done"))
	system(("convert $(for f in $(seq "1" "d["pageCount"]"); do echo "e"/page_${f}.jpg; done) \""d["title"]".pdf\""))
	system(("rm -rf "e))
}
