#!/usr/bin/gawk -f

BEGIN {
        while(("wget --quiet -O- "ARGV[1]) | getline) {
                if(index($0, "pageCount")) {
                        a = split($0, b, ",")
                        for(c = 1; c <= a; c++) {
                                split(b[c], d, "[;|:|&]")
                                if(d[3] == "pageCount") { ind = 2 } else { ind = 0 }
                                if(d[3] == "title" && ++titleCnt > 1) break
                                e[d[3]] = d[8-ind]
                        }
                        break
                }
        }

        "mktemp -d" | getline f
        for(g = 1; g <= e["pageCount"]; g++) {
                system(("wget --quiet -P "f" https://image.isu.pub/"e["revisionId"]"-"e["publicationId"]"/jpg/page_"g".jpg"))
        }
        system(("convert $(for h in $(seq "1" "e["pageCount"]"); do echo "f"/page_${h}.jpg; done) \""e["title"]".pdf\""))
        system(("rm -rf "f))
}
